import express from "express";
const carRoute = express.Router();
import carCotroller from "/Users/faycalabdelhadinemouchi/Documents/nodeProjects/CarRentalProject/controllers/carController.js";
carRoute.get("/all-cars",carCotroller.showAllCars);
carRoute.post("/add-car",carCotroller.addCar);
carRoute.get("/car-details/:cid",carCotroller.cad_datails);
carRoute.delete("/emove-car/:cid",carCotroller.delete_car);
carRoute.get("/Admin-All-Cars-number",carCotroller.admine_total_cars_num);
carRoute.get("/Admin-All-Cars",carCotroller.admine_total_cars);
carRoute.get("/search-by-name",carCotroller.search_car_by_name);
carRoute.get("/fiter-cars",carCotroller.filter_car);
export default carRoute;